# Site settings
title: Ricardo N. M.
email: contato@ricardonm.com.br
url: https://ricardonm.com.br
description: "Site for a web and mobile developer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static
thanks: Thanks!
thanks-description: 'I will reply as soon as possible.'

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Localização
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.facebook.com/nm.ricardo
  - title: linkedin
    url: http://br.linkedin.com/in/nmricardo
  - title: github
    url: http://github.com/spitfire2903
  - title: stack-overflow
    url: http://stackoverflow.com/users/4471536/ricardo-nunes-de-miranda# http://stackoverflow.com/questions/tagged/spitfire2903
  #- title: bitbucket
  #  url: http://bitbucket.org/spitfire2903
  - title: twitter
    url: http://twitter.com/ricardonmiranda


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
